/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agileassignment;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.lang.String;

/**
 *
 * @author yipki
 */
public class StaffSalesOrder extends javax.swing.JFrame {

    /**
     * Creates new form StaffSalesOrder
     */
    public StaffSalesOrder() {
        initComponents();
        //showDate();
        //
       // addRowToTable();
        
    }
    
    public class OrderList{
        
        public String TransactionNo;
        public String CustomerName;
        public String CreatedOn;
        
        public OrderList(String TransactionNo, String CustomerName, String CreatedOn){
            this.TransactionNo = TransactionNo;
            this.CustomerName = CustomerName;
            this.CreatedOn = CreatedOn;
            
        }
    }
        public ArrayList PickUpList(){
            ArrayList<OrderList> list = new ArrayList<OrderList>();
            OrderList ordList1 = new OrderList("OD00001","Kee Woi Chen","1/12/2018");
            OrderList ordList2 = new OrderList("OD00002","Tan Hooi Xin","1/12/2018");
            OrderList ordList3 = new OrderList("OD00003","E-Company","2/12/2018");
            OrderList ordList4 = new OrderList("OD00004","TARUC","2/12/2018");
            
            list.add(ordList1);
            list.add(ordList2);
            list.add(ordList3);
            list.add(ordList4);
            return list;
        }
        
        public void addRowToTable(){
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        ArrayList<OrderList> list = PickUpList();
        Object rowData[] = new Object[5];
            
        model.setRowCount(0);
        for(int i=0; i<list.size(); i++){
            if(jcbdate.getSelectedItem().toString().equals(list.get(i).CreatedOn)){
             rowData[0] = list.get(i).TransactionNo;
                rowData[1] = list.get(i).CustomerName;
                rowData[2] = list.get(i).CreatedOn;
                

                model.addRow(rowData);
            }
        }
            
        }
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcbdate = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransactionNo", "CustomerName", "CreatedOn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sales Order List");

        jLabel2.setText("Date");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "1/12/2018", "2/12/2018", "3/12/2018", "4/12/2018" }));
        jcbdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(545, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        int dialogButton = JOptionPane.showConfirmDialog(null, "View " + value1 + " sales order ?");
        
        //
        if(dialogButton == JOptionPane.YES_OPTION) {
            if(value1.equals("OD00001")){
                //JOptionPane.showMessageDialog(null, "go to 01");
                String tran = "OD00001";
                //String custname = "Kee Woi Chen";
                SalesOrder salesOrder = new SalesOrder();
                salesOrder.setTransfer(tran);
                //salesOrder.setTransfer(custname);
                salesOrder.setVisible(true);
                
            }
            else if(value1.equals("OD00002")){
                //JOptionPane.showMessageDialog(null, "go to 02");
                String tran = "OD00002";
                //String custname = "Tan Hooi Xin";
                SalesOrder salesOrder = new SalesOrder();
                salesOrder.setTransfer(tran);
                //salesOrder.setTransfer(custname);
                salesOrder.setVisible(true);
            }
               //JOptionPane.showMessageDialog(null, "boleh");
        }
        
        
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String value1 = model.getValueAt(index, 0).toString();
        int dialogButton = JOptionPane.showConfirmDialog(null, "View " + value1 + " sales order ?");
        
        //
        if(dialogButton == JOptionPane.YES_OPTION) {
            if(value1.equals("OD00001")){
                //JOptionPane.showMessageDialog(null, "go to 01");
                String tran = "OD00001";
                //String custname = "Kee Woi Chen";
                SalesOrder salesOrder = new SalesOrder();
                salesOrder.setTransfer(tran);
                //salesOrder.setTransfer(custname);
                salesOrder.setVisible(true);
                
            }
            else if(value1.equals("OD00002")){
                //JOptionPane.showMessageDialog(null, "go to 02");
                String tran = "OD00002";
                //String custname = "Tan Hooi Xin";
                SalesOrder salesOrder = new SalesOrder();
                salesOrder.setTransfer(tran);
                //salesOrder.setTransfer(custname);
                salesOrder.setVisible(true);
            }
               //JOptionPane.showMessageDialog(null, "boleh");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdateActionPerformed
         
        addRowToTable();
    }//GEN-LAST:event_jcbdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffSalesOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbdate;
    // End of variables declaration//GEN-END:variables
}
